### ISSUE TITLE
Allow light bar to be on when vehicle is off

### ISSUE THREAD

**Issue by msmcconnell** [usdot-fhwa-stol/CARMAPlatform#103]
### Descriptive summary
For TRB demonstration purposes we want to allow the light bar to be turned on when the vehicle is off.

### Expected behavior
Light bar can be controlled even when vehicle is off

### Actual behavior
Light bar turns off when vehicle is not under automated control

### Steps to reproduce the behavior

Launch controller then try using the light bar without entering automated control

**Comment by qswawrq** [comment]
Resolved by #104
