### ISSUE TITLE
Traffic Signal Plugin: Vehicle goes slowly through intersections. 

### ISSUE THREAD

**Issue by msmcconnell** [usdot-fhwa-stol/CARMAPlatform#109]
When trying to catch the light on the second intersection the vehicle may slow down in the first intersection. This could disrupt traffic flow. The algorithm could be enhanced to handle this.

**Comment by darrelld05** [comment]
This issue was transferred from:
https://api.github.com/repos/usdot-fhwa-stol/CARMAPlatformOld2
Old issue # 1081

**Comment by msmcconnell** [comment]
Closed as OBE in carma3 and noted on the CARMA2 tracker spreadsheet
