### ISSUE TITLE
Traffic Signal Plugin: There is a dip in speed before entering the last intersection

### ISSUE THREAD

**Issue by msmcconnell** [usdot-fhwa-stol/CARMAPlatform#110]
When traveling at higher speed the plugin will drop the speed by within 5mph just before the last intersection. This feels very unnatural and should be removed.

**Comment by darrelld05** [comment]
This issue was transferred from the original CARMAPlatform: Old issue # 1080

**Comment by maefromm** [comment]
@msmcconnell closing out the JIRA task due to "CARMA2 closeout. Most likely OBE or will revisit if need in CARMA3" Would you like to keep this open?

**Comment by msmcconnell** [comment]
Closed as OBE in carma3 and noted on the CARMA2 tracker spreadsheet
