### ISSUE TITLE
Traffic Signal Plugin: Speed commands should be smoothed

### ISSUE THREAD

**Issue by msmcconnell** [usdot-fhwa-stol/CARMAPlatform#111]
The A* search to optimize fuel use for the traffic signal plugin sometimes generates unnatural speed changes such as 18 ->16 -> 19. Such changes should be smoothed out before execution.

**Comment by darrelld05** [comment]
This issue was transferred from the original CARMAPlatform: Old issue # 1079

**Comment by maefromm** [comment]
@msmcconnell closing out the JIRA task due to "CARMA2 closeout. Most likely OBE or will revisit if need in CARMA3" Would you like to keep this open?

**Comment by msmcconnell** [comment]
Closed as OBE in carma3 and noted on the CARMA2 tracker spreadsheet
