### ISSUE TITLE
Light bar does not flash green when receiving bsms

### ISSUE THREAD

**Issue by msmcconnell** [usdot-fhwa-stol/CARMAPlatform#113]
The state machine for the light bar says that when receiving BSMs and engaged the green light should flash. This has not been happening recently.

**Comment by darrelld05** [comment]
This issue was transferred from the original CARMAPlatform: Old issue # 1077

**Comment by msmcconnell** [comment]
Closed as OBE in carma3 and noted on the CARMA2 tracker spreadsheet
