### ISSUE TITLE
Ensure all nodes using get_drivers_with_capabilities are searching correctly by name.

### ISSUE THREAD

**Issue by maefromm** [usdot-fhwa-stol/CARMAPlatform#117]
Discussion with Mike, need to search the carma repo (java and cpp) to ensure any nodes calling "get_drivers_with_capabilities" are searching correctly by name instead of by position. When searching, it should not include the capability. 

For example, in Message Node it should have endsWith(comms/inbound_binary_msgs) instead of endsWith("/dsrc/comms/inbound_binary_msg").

**Comment by darrelld05** [comment]
This issue was transferred from the original CARMAPlatform: Old issue # 1050

**Comment by TonysCousin** [comment]
This is no longer a problem in CARMA3 since we have removed the driver discovery capability.
