### ISSUE TITLE
Arbitrator does not respect the presence of complex maneuvers when replanning

### ISSUE THREAD

**Issue by msmcconnell** [usdot-fhwa-stol/CARMAPlatform#128]
During TO 26 testing the cooperative merge plugin tried to place complex maneuvers in a trajectory, however route following would always try to extend the trajectory further. Because maneuvers cannot be placed after a complex maneuver these trajectories fail. This is repeated until 5 trajectories fail and arbitrator throws a exception. Ideally route following would not be allowed to try to extend the trajectory in this case. 

Edit: This issue was identified as the root cause of Issue #905

**Comment by darrelld05** [comment]
This issue was transferred from the original CARMAPlatform: Old issue # 915

**Comment by msmcconnell** [comment]
Closed as OBE in carma3 and noted on the CARMA2 tracker spreadsheet
