### ISSUE TITLE
Trajectory extension for request messages needs to better obey Mobility Strategy

### ISSUE THREAD

**Issue by msmcconnell** [usdot-fhwa-stol/CARMAPlatform#134]
When a MobilityRequest is received beyond the end of the current trajectory, the trajectory is extended to check for conflicts. However, the only plugin capable of responding to a detected conflict during the replan is the default conflict handler (Yield). This is undesirable as the plugin the request was intended for should be the one allowed to plan in that region. We need a way to associate the request message data with the detected conflict. Some of this is already saved like the sender id and plan id in ConflictManager, but we also need the strategy string to route the planning to the correct plugin.

**Comment by darrelld05** [comment]
This issue was transferred from the original CARMAPlatform: Old issue # 871

**Comment by msmcconnell** [comment]
Closed as OBE in carma3 and noted on the CARMA2 tracker spreadsheet
