### ISSUE TITLE
Guidance pub sub needs message type validation for topics and services

### ISSUE THREAD

**Issue by msmcconnell** [usdot-fhwa-stol/CARMAPlatform#139]
Because the underlying rosjava subscription/publication object is shared between guidance components, it is possible for one component to cause a class cast exception in another if the two components expect different message types on the same topic. This generates a very cryptic error such as the one below.
```
java.lang.ClassCastException: org.ros.internal.message.$Proxy61 cannot be cast to cav_msgs.MobilityResponse
    at gov.dot.fhwa.saxton.carma.guidance.mobilityrouter.MobilityRouter.lambda$fireMobilityRequestCallback$0(MobilityRouter.java:196)
    at java.lang.Thread.run(Thread.java:748)
```
To avoid this the pub sub manager should cache all subscribed topic names, and assign a message type. This topic name should probably be fully defined to allow for namespaces. If a future user wishes to use a different message type a clearly described error should be thrown.

**Comment by darrelld05** [comment]
This issue was transferred from the original CARMAPlatform: Old issue # 829

**Comment by msmcconnell** [comment]
Closed as OBE in carma3 and noted on the CARMA2 tracker spreadsheet
