### ISSUE TITLE
Improve tuning of ACC

### ISSUE THREAD

**Issue by msmcconnell** [usdot-fhwa-stol/CARMAPlatform#144]
The ACC system of carma could have it's stability improved. After, the speed controller and acc were tuned at Aberdeen on April 16th and 17th of 2018. The speed controller comfort was dramatically improved. ACC fixes were implemented in PR #764. ACC was brought to an acceptable level according to Tim. We were running at 45 and 60 mph.

However, their is still room for improvement. The system demonstrates large oscillations and some instability. This seems to mostly be due to a lag between guidance commands and the speed controller. This is likely due to the ACC system utilizing a PID on speed commands. This controller results in small changes in the target speed of the TORC speed controller. This leads to low errors and poor response time. The best fix would be moving the ACC system to wrench effort based commands. This would remove the stacked PID loops and allow for a better response and more effective tuning of the system.

**Comment by darrelld05** [comment]
This issue was transferred from the original CARMAPlatform: Old issue # 811

**Comment by msmcconnell** [comment]
Closed as OBE in carma3 and noted on the CARMA2 tracker spreadsheet
