### ISSUE TITLE
Speed Limit Counter not working 

### ISSUE THREAD

**Issue by maefromm** [usdot-fhwa-stol/CARMAPlatform#146]
Per ATEF drivers, not counting up or down and just displaying 0.

**Comment by darrelld05** [comment]
This issue was transferred from the original CARMAPlatform: Old issue # 773

**Comment by maefromm** [comment]
@TonysCousin This is the "Speed Limit Change In: x.xx mi/xxx mi" Last I tested, it is working just fine. This is no longer an issue. Thanks.
