### ISSUE TITLE
Display of system alert on startup

### ISSUE THREAD

**Issue by TonysCousin** [usdot-fhwa-stol/CARMAPlatform#147]
When trying to start Carma this morning we ran into several instances of the UI informing "unable to find SYSTEM READY message" or something similar.  The root cause was the pinpoint was in a fault status, but required looking through logs to determine. It would be nice to have the UI display the content from the SYSTEM_ALERT message when one is received to make diagnosis quicker.

**Comment by darrelld05** [comment]
This issue was transferred from the original CARMAPlatform: Old issue # 772

**Comment by maefromm** [comment]
I think this can be closed since this is from CARMA2 and have not run into this lately with CARMA3.
