### ISSUE TITLE
Route specification cannot handle edge case

### ISSUE THREAD

**Issue by msmcconnell** [usdot-fhwa-stol/CARMAPlatform#152]
The route specification cannot describe a lane change where the number of lanes does not change and the lane index does not change. (The vehicle is not aware of this lane change)

**Comment by darrelld05** [comment]
This issue was transferred from the original CARMAPlatform: Old issue # 475

**Comment by msmcconnell** [comment]
Closed as OBE in carma3 and noted on the CARMA2 tracker spreadsheet
