### ISSUE TITLE
SpeedHarmonization server Linear algorithm behavior did not match expected behavior. (Aberdeen SpeedHarm Test)

### ISSUE THREAD

**Issue by msmcconnell** [usdot-fhwa-stol/CARMAPlatform#153]
When testing the Speed Harmonization Plugin at ATEF the Linear Speed Change Algorithm did not seem to change its behavior based on modifications to the algorithms.properties file located in the same folder as the jar. This made testing difficult but a workaround was found by creating a new algorithm which reduced the vehicles speed by 5mph.

**Comment by darrelld05** [comment]
This issue was transferred from the original CARMAPlatform: Old issue # 418

**Comment by msmcconnell** [comment]
Closed as OBE in carma3 and noted on the CARMA2 tracker spreadsheet
