### ISSUE TITLE
CTE consequences should be handled by Tracking

### ISSUE THREAD

**Issue by TonysCousin** [usdot-fhwa-stol/CARMAPlatform#155]
Route computes cross track error, which is appropriate, but it should not be initiating system shutdown based on the value.  Guidance.Tracking is where decisions are made about whether the vehicle is too far off plan.  All of this decision logic should be consolidated in this one class.

**Comment by darrelld05** [comment]
This issue was transferred from the original CARMAPlatform: Old issue # 365

**Comment by msmcconnell** [comment]
Closed as OBE in carma3 and noted on the CARMA2 tracker spreadsheet
