### ISSUE TITLE
YAML route names cannot include underscores (Aberdeen CR 29)

### ISSUE THREAD

**Issue by TonysCousin** [usdot-fhwa-stol/CARMAPlatform#157]
The YAML library doesn't allow underscore characters in names assigned inside the file (filenames themselves are okay). We need to include user instructions to clarify this requirement for people building route definitions. Alternatively, this may be another reason to switch to using CSV format for route files.

**Comment by darrelld05** [comment]
This issue was transferred from the original CARMAPlatform: Old issue # 333

**Comment by msmcconnell** [comment]
Closed as OBE in carma3 and noted on the CARMA2 tracker spreadsheet
