### ISSUE TITLE
Document startup procedure (Aberdeen CR 8)

### ISSUE THREAD

**Issue by TonysCousin** [usdot-fhwa-stol/CARMAPlatform#159]
Suggestion to provide a checklist of procedures on the tablet.  This may be better served by handing out a printed QRC, since instructions may need to be changed frequently. 11/14/17 CCB: This is better as a document.  Can have a hand-held sheet, but also make it a PDF on the tablet.

**Comment by darrelld05** [comment]
This issue was transferred from the original CARMAPlatform: Old issue # 325

**Comment by msmcconnell** [comment]
@TonysCousin Does this issue still apply given our User Guide?

**Comment by maefromm** [comment]
I think for now we can close this. We have documentation tasks that we need to do now for CARMA3. And CARMA2 UI guide which this was using is already updated.
