### ISSUE TITLE
Need for a clean shutdown of nodes on Sensor Fusion. 

### ISSUE THREAD

**Issue by maefromm** [usdot-fhwa-stol/CARMAPlatform#160]
During verification test on 11/7/2017, we discovered both Guidance and Sensor Fusion wasn't cleanly shutting down.

**Comment by darrelld05** [comment]
This issue was transferred from the original CARMAPlatform: Old issue # 256

**Comment by msmcconnell** [comment]
sensor_fusion node was removed in CARMA3 so close as OBE and noted on the CARMA2 tracker spreadsheet
