### ISSUE TITLE
Build system doesn't run gradle tests

### ISSUE THREAD

**Issue by Supraluminal** [usdot-fhwa-stol/CARMAPlatform#164]
`catkin_make run_tests` doesn't trigger the execution and collection of the tests normally run by the `./gradlew test` command. This means CircleCI doesn't get a report on our test results.

#77 attempts to address this but is incomplete.

**Comment by darrelld05** [comment]
This issue was transferred from the original CARMAPlatform: Old issue # 79

**Comment by Supraluminal** [comment]
Resolved now that CircleCI has been configured to run Java tests and record test reports.
