### ISSUE TITLE
Truck CAN/controller driver interface is not the same as SRX drivers

### ISSUE THREAD

**Issue by qswawrq** [usdot-fhwa-stol/CARMAPlatform#166]
Truck drivers and SRX drivers have different topic name for some output data. For example, truck controller subscribes to speed_accel topic but SRX drivers subscribes to cmd_speed topic for cmd_speed input.
Truck drivers and SRX drivers have different units on the same topic. For example, truck CAN reports current speed in km/h but SRX reports them in m/s.
There are more mismatch on unit and topic name. We need to verify all necessary topic to make sure they have the same interface.

**Comment by darrelld05** [comment]
Closed per Kyle...not an issue
