### ISSUE TITLE
Security risk on incoming mobility messages

### ISSUE THREAD

**Issue by TonysCousin** [usdot-fhwa-stol/CARMAPlatform#202]
### Descriptive summary
Feb 2019 SonarCloud scan of the code base identified a security hotspot where a regex is being used to scan mobility message strategy strings, and allowing anything in that is between commas (splitting it into comma-separated key/value pairs).  Investigation of this logic led to several places in RSUMetering and CooperativeMerge plugins where these values are used unchecked.  Some of the values have the potential to drastically affect how the vehicle behaves.

### Expected behavior
The plugins should do a sanity check on the incoming strategy values to improve confidence that they are legitimate.

### Actual behavior
Received strategy values are used as-is with no verification.

### Steps to reproduce the behavior
Software execution is not necessary.  Review Sonarcloud scan from Feb 2019 to see the item (https://sonarcloud.io/project/issues?id=usdot-fhwa-stol_CARMAPlatform&open=AWi6MsbKa3c5WIT7ymyM&resolved=false&severities=CRITICAL&types=VULNERABILITY)

### Related work

None.

**Comment by darrelld05** [comment]
removed the label

**Comment by msmcconnell** [comment]
@TonysCousin Has this been resolved?

**Comment by msmcconnell** [comment]
My understanding from PR #212 is that this issue is resolved. Will close.
