### ISSUE TITLE
Pinpoint reports lat/lon values of 0; JIRA Issue: #CAR-222

### ISSUE THREAD

**Issue by darrelld05** [usdot-fhwa-stol/CARMAPlatform#217]
### Descriptive summary
On the Green Cadillac (and perhaps the White one as well, but not as frequently or as long in duration) the lat/lon values reported by the Pinpoint do not change from 0. This occurs with PPP corrections on or off.
The root cause of this has not been discovered yet. On 11/30/18, using Telnet, an FRESET command (factory reset) was sent to the Novatel GPS card inside the Pinpoint. However, this did not make the problem go away.
To close this anomaly, we should know what has caused the lat/lon values to be reported as 0 and how to fix this. On the other hand, if the reason for this is not discovered, but upon some changes the problem goes away completely for an extended period of time, then anomaly may also be considered closed.

**Comment by msmcconnell** [comment]
Closed as OBE in carma3 and noted on the CARMA2 tracker spreadsheet
