### ISSUE TITLE
Pinpoint becomes unresponsive during operation with PPP corrections enabled; JIRA Issue: #CAR-53

### ISSUE THREAD

**Issue by darrelld05** [usdot-fhwa-stol/CARMAPlatform#218]
### Descriptive summary
Pinpoint stops responding to any network communications after some period of time running on firmware P25 with PPP corrections enabled, requires hard restart to fix.

**Comment by msmcconnell** [comment]
Closed as OBE in carma3 and noted on the CARMA2 tracker spreadsheet
