### ISSUE TITLE
Cohda OBU locks up during operation; JIRA Issue: #CAR-52

### ISSUE THREAD

**Issue by darrelld05** [usdot-fhwa-stol/CARMAPlatform#219]
### Descriptive summary
Cohda OBU fails to forward received messages or broadcast outgoing messages after some period of operation. Requires a hard reboot to fix.

**Comment by msmcconnell** [comment]
I believe this is an old issue which was only present on the original MK5 RSU firmware. I am not aware of it being an issue on the current firmware. 

Closed as OBE in carma3 and noted on the CARMA2 tracker spreadsheet
