### ISSUE TITLE
All longitudinal maneuvers account for vehicle response delay even if it isn't necessary; JIRA Issue: #CAR-47 

### ISSUE THREAD

**Issue by darrelld05** [usdot-fhwa-stol/CARMAPlatform#220]
### Descriptive summary
All longitudinal maneuvers plan for 1.4s of the vehicle being non-responsive to control input prior to calculating the start of their acceleration or deceleration. This may only be necessary when it can be assumed that the vehicle's acceleration at the start of the maneuver is 0 m/s/s, if the maneuver is a continuation of an ongoing acceleration or deceleration this delay may already be accounted for by a previous maneuver or the delay may not be as substantial as 1.4s.
This may cause maneuvers to fail validation or fail to meet planned intent.

**Comment by msmcconnell** [comment]
Closed as OBE in carma3 and noted on the CARMA2 tracker spreadsheet
