### ISSUE TITLE
Epsilon factor in SimpleManeuverFactory can cause illegal maneuvers to be made out of legal ones; JIRA Issue: #CAR-46

### ISSUE THREAD

**Issue by darrelld05** [usdot-fhwa-stol/CARMAPlatform#221]
### Descriptive summary
Description: Due to the delta-V epsilon comparison in SimpleManeuverFactory a legal slow down maneuver can be coerced into being an illegal steady speed maneuver at plan time.

**Comment by msmcconnell** [comment]
Closed as OBE in carma3 and noted on the CARMA2 tracker spreadsheet
