### ISSUE TITLE
Invalid XML in ndt_pose_tf_wrapper package.xml; JIRA Issue#: CAR-819

### ISSUE THREAD

**Issue by Supraluminal** [usdot-fhwa-stol/CARMAPlatform#253]
### Types of Issue

- [x] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary
`ndt_pose_tf_wrapper` package.xml contains invalid XML causing a failing build.

### Expected behavior
Successful docker build.
### Actual behavior
Catkin make errors out at line 1 character 1 of `ndt_pose_tf_wrapper/package.xml` because of comments with "#" instead of "".

### Steps to reproduce the behavior

1. Checkout CARMAPlatform repository
1. Run `./docker/build-image.sh`

**Comment by qswawrq** [comment]
Fixed by #258
