### ISSUE TITLE
Broken unit tests on release RX7 branch

### ISSUE THREAD

**Issue by qswawrq** [usdot-fhwa-stol/CARMAPlatform#292]
### Types of Issue

- [x] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary
Due to recent changes and fixes on release, the anticipated behaviors changed in both autoware plugin package and pure pursuit wrapper package, such that some unit tests are not working correctly throwing error reports.
### Expected behavior
All unit tests should pass.
### Actual behavior
Some unit tests fail.
### Steps to reproduce the behavior
Run ```catkin_make run_tests``` on those two packages.
### Related work
N/A

**Comment by msmcconnell** [comment]
Resolved by PR #293
