### ISSUE TITLE
Behavior discrepancy between original autoware and CARMA pre-release

### ISSUE THREAD

**Issue by qswawrq** [usdot-fhwa-stol/CARMAPlatform#333]
### Types of Issue

- [x] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary
CARMA 3 utilizes the same planning and control data flow as Autoware. However, the actual behavior for the same route is not the same. CARMA 3 tends to overshoot in certain area on the route, which results in driving in the middle of the road or on the grass. It is not clear it is a pure configuration issue or a deeper problem. Sensor measurements and SSC parameters on Pacifica are checked and they have the same value.
### Expected behavior
CARMA 3 pre-release version should have the same path following behavior as native Autoware.
### Actual behavior
CARMA 3 performs poorly comparing to Autoware
### Steps to reproduce the behavior
Run the same route with Autoware and CARMA 3,
### Related work
N/A

**Comment by msmcconnell** [comment]
Resolved as far is practical by the above linked prs.
