### ISSUE TITLE
In order to see available plugins UI must be refreshed

### ISSUE THREAD

**Issue by msmcconnell** [usdot-fhwa-stol/CARMAPlatform#347]
### Types of Issue

- [x] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary
This issue appears on develop. When starting carma the route will appear as normal on the UI, but in order to see the available plugins the UI must be refreshed. The following UI steps proceed as normal.

### Expected behavior
No refresh required in any usage of the UI
### Actual behavior
Refresh to see plugin list
### Steps to reproduce the behavior

Run develop in docker version of carma (untested in src). Try to use the UI

### Related work

Link to related tickets or prior related work here.

**Comment by maefromm** [comment]
Issue appeared before plugin discovery was implemented in the Autoware Plugin. Issue is now gone after it was properly implemented.
