### ISSUE TITLE
Autoware plugin does not support plugin discovery

### ISSUE THREAD

**Issue by msmcconnell** [usdot-fhwa-stol/CARMAPlatform#348]
### Types of Issue

- [x] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary
The Autoware plugin has not been updated to use the new plugin discovery mechanism and therefore a topic publication work around must be used to operate it
### Expected behavior
Autoware plugin self reports itself to guidance
### Actual behavior
Autoware plugin must be specified via topic publish from user or launch file
### Steps to reproduce the behavior

Run develop build of carma

**Comment by msmcconnell** [comment]
PR #351 contains a temporary work around for this issue and does not resolve the root cause. Once the plugin is updated to support this functionality, the rostopic pub command added to guidance.launch in that PR should be removed.

**Comment by maefromm** [comment]
Per @qswawrq, this has been resolved by https://github.com/usdot-fhwa-stol/CARMAPlatform/pull/363
