### ISSUE TITLE
Guidance state machine does not transition properly from active to engaged on Lexus

### ISSUE THREAD

**Issue by msmcconnell** [usdot-fhwa-stol/CARMAPlatform#349]
### Types of Issue

- [x] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary
The guidance node uses a state machine developed for CARMA2 which expects user confirmation via hardware button in the vehicle. This is not present on the Lexus and as such the state machine is not currently functional
### Expected behavior
On Lexus hitting the Guidance button on the UI will change the vehicle to the engaged state
### Actual behavior
Guidance will only enter Active state when controlled through the UI
### Steps to reproduce the behavior
Run develop branch of carma

**Comment by itabrl** [comment]
New update will fix this issue.

**Comment by maefromm** [comment]
Fixed by https://github.com/usdot-fhwa-stol/CARMAPlatform/pull/362
