### ISSUE TITLE
CARMA launch file does not provide placeholder to pass map cell paths

### ISSUE THREAD

**Issue by qswawrq** [usdot-fhwa-stol/CARMAPlatform#352]
### Types of Issue

- [ ] Anomaly report (something appears to not work correctly)
- [x] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary
In map_file package, ndt_matching.launch accepts map cell path as a ROS launch parameter. But top level carma launch file does not has this parameter placeholder.
### Expected behavior
Top level launch file should provide parameter placeholder to easily add new map cell paths.
### Actual behavior
Top level launch file does not provide parameter placeholder to easily add new map cell paths.
### Steps to reproduce the behavior
N/A
### Related work
N/A

**Comment by qswawrq** [comment]
Current map loader does not need this rosparam.

**Comment by msmcconnell** [comment]
Functionality was added in usdot-fhwa-stol/autoware.ai#6
