### ISSUE TITLE
CI build fails due to missing ros-kinetic-swri-serial-util pkg

### ISSUE THREAD

**Issue by qswawrq** [usdot-fhwa-stol/CARMAPlatform#358]
### Types of Issue

- [x] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary
CI build fails because it cannot pull down one of the dependency: ros-kinetic-swri-serial-util:
```The following NEW packages will be installed:
  ros-kinetic-swri-serial-util
0 upgraded, 1 newly installed, 0 to remove and 17 not upgraded.
Need to get 16.4 kB of archives.
After this operation, 67.6 kB of additional disk space will be used.

Err:1 http://packages.ros.org/ros/ubuntu xenial/main amd64 ros-kinetic-swri-serial-util amd64 2.9.0-1xenial-20190607-172500-0800
  404  Not Found [IP: 64.50.233.100 80]

E: Failed to fetch http://packages.ros.org/ros/ubuntu/pool/main/r/ros-kinetic-swri-serial-util/ros-kinetic-swri-serial-util_2.9.0-1xenial-20190607-172500-0800_amd64.deb  404  Not Found [IP: 64.50.233.100 80]

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
ERROR: the following rosdeps failed to install
  apt: command [sudo -H apt-get install -y ros-kinetic-swri-serial-util] failed
Exited with code 1
```
However, the same command works on local VM: ```rosdep install --from-paths src --ignore-src -y```
It is not clear if it is just a temporary issue but it causes the current develop build failed.
### Expected behavior
CI should be able to pull down all dependencies correctly.
### Actual behavior
CI could not find ros-kinetic-swri-serial-util.
### Steps to reproduce the behavior
Check current CicleCI Build Status.
### Related work
N/A

**Comment by msmcconnell** [comment]
Resolved by PR #359
