### ISSUE TITLE
Skyline Release - Deployment and Configuration Changes

### ISSUE THREAD

**Issue by maefromm** [usdot-fhwa-stol/CARMAPlatform#373]
### Types of Issue

- [ ] Anomaly report (something appears to not work correctly)
- [x] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary
1. Update the autoware.ai mapfile param.yaml to use the latest map file. 
2. Update to use ndt_node only, instead of auto mode. 
3. Address any other configuration changes required to properly deploy the Skyline release to all the vehicles. 

### Related work
Ensure all the final code for this release have been checked in and tested.

**Comment by TonysCousin** [comment]
@maefromm I changed the title from "fixes" to "changes" since a fix implies there is a defect. In fact, I see these as enhancements (since nothing is broken), so marked the ticket as such.

**Comment by maefromm** [comment]
This can be closed with the Skyline being merged to master and the fix on 374.
