### ISSUE TITLE
SonarCloud code coverage does not work porperly

### ISSUE THREAD

**Issue by qswawrq** [usdot-fhwa-stol/CARMAPlatform#375]
### Types of Issue

- [x] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary
SonarCloud does not report code coverage correctly. On health_monitor package, we have unit tests to cover large part of the code. However, it is reported as 0.0% on that branch:
https://sonarcloud.io/component_measures?id=usdot-fhwa-stol_CARMAPlatform&metric=new_coverage&pullRequest=364&selected=usdot-fhwa-stol_CARMAPlatform%3Ahealth_monitor
It also cause the overall code coverage drop after merge.
### Expected behavior
SonarCloud reports code coverage correctly.
### Actual behavior
SonarCloud reports code coverage incorrectly.
### Steps to reproduce the behavior
N/A
### Related work
N/A

**Comment by msmcconnell** [comment]
@qswawrq Are you sure the CI fully ran as long as #369 remains unfixed there will not be any metrics reported.
