### ISSUE TITLE
Fix CARMA repo readme files to follow the same format

### ISSUE THREAD

**Issue by maefromm** [usdot-fhwa-stol/CARMAPlatform#388]
### Types of Issue

- [ ] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [x] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories) 

### Descriptive summary
The following repos need the readme's updated to match the other repo format. 
https://github.com/usdot-fhwa-stol/autoware.ai (Different format)
https://github.com/usdot-fhwa-stol/CARMANovatelGpsDriver (Different format)
https://github.com/usdot-fhwa-stol/CARMAAvtVimbaDriver (No readme)

### Expected behavior
Have same readme or landing page format across repos. 

### Software version this applies to

NA

### Steps to reproduce the behavior
1. Visit the sites above and make sure it follows the same layout as CARMAPlatform or others. 

### Related work
Link to related tickets or prior related work here.
NA

**Comment by msmcconnell** [comment]
Those repos are all forks of 3rd party repos. It's worth considering whether we can add to them rather than replace them. The novatel readme for example serves as the primary documentation for that driver and needs to be preserved.

**Comment by maefromm** [comment]
Resolved with the following PRs. 

Repo: CARMAAvtVimbaDriver
PR Merge Notice:  #16 from usdot-fhwa-stol/feature/StandardizeReadme

Repo: autoware.ai
PR Merge Notice: #25 Feature/standardize readme 

Repo: CARMANovatelGpsDriver
PR Merge Notice: #32 from usdot-fhwa-stol/feature/StandardizeReadme
