### ISSUE TITLE
Update docker to use Autoware 1.12 build

### ISSUE THREAD

**Issue by qswawrq** [usdot-fhwa-stol/CARMAPlatform#416]
### Types of Issue

- [ ] Anomaly report (something appears to not work correctly)
- [x] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary
Since we have a new Autoware 1.12 component release, we need to update the Dockerfile in this repo to build the CARMAPlatform docker image based on the new Autoware image.
### Expected behavior
CARMAPlatform docker builds on Autoware docker v3.3.0.
### Software version this applies to

CARMASystem_3.1.0
### Actual behavior
CARMAPlatform docker currently builds on Autoware docker v3.2.0.
### Steps to reproduce the behavior
N/A
### Related work
N/A

**Comment by msmcconnell** [comment]
Resolved by PR #417
