### ISSUE TITLE
End of Trajectory Exception during middle of the route

### ISSUE THREAD

**Issue by qswawrq** [usdot-fhwa-stol/CARMAPlatform#476]
### Types of Issue

- [x] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary
Vehicle throws an end of trajectory exception if human driver takes over control of the vehicle during the middle of the route and not reengage in ~6 seconds.
### Expected behavior
After human driver takes over control of the vehicle, he can reengage at any time he wants.
### Software version this applies to

CARMAPlatform_testarossa
### Actual behavior
If human driver did not reengage in time, trajectory executor will throw an end of trajectory exception.
### Steps to reproduce the behavior
After vehicle is running, override manually and wait for ~6 seconds. The error should pop up in UI as a fatal message.

### Related work
#300 is a similar issue due to the lack of route state awareness in trajectory executor.

**Comment by aswath1** [comment]
The issue is fixed through PR : release/testarossa - component fix for trajectory error and ensuring docker id is 999 #480
