### ISSUE TITLE
CARMAAvtVimbaDriver Build Image Name is Incorrect

### ISSUE THREAD

**Issue by maefromm** [usdot-fhwa-stol/CARMAPlatform#482]
### Types of Issue

- [x] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary
Found this issue during the build-image.sh of this repo. Forgot to followup on this fix with JB when working with him last Friday, 13th.

### Expected behavior
should have dashes in the image name, carma-avt-vimba-driver 

### Software version this applies to

testarossa

### Actual behavior
showing  as usdotfhwastol/carmaavtvimbadrive

### Steps to reproduce the behavior

Run build-image.sh

### Related work

Link to related tickets or prior related work here.

**Comment by aswath1** [comment]
Fix PR: fix build image name #25

**Comment by maefromm** [comment]
@jtbaird has confirmed the build I pushed is out on the right repo.
