### ISSUE TITLE
Create configuration of carma-platform capable of operating on the freightliner cascadia using two lidars

### ISSUE THREAD

**Issue by msmcconnell** [usdot-fhwa-stol/CARMAPlatform#489]
### Types of Issue

- [ ] Anomaly report (something appears to not work correctly)
- [x] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary
STOL has aquired an freightliner cascadia from autonomous stuff which requires two lidars for localization. A new configuration folder and calibration folder are needed to support running carma on this system. 
### Expected behavior
CARMAPlatform can run on the truck and perform waypoint following. 
### Software version this applies to

CARMASystem_3.2.+
### Actual behavior
No valid configuration currently exists.

**Comment by Supraluminal** [comment]
Closing after successful week of testing by @msmcconnell and @maefromm
