### ISSUE TITLE
libproj.so can not be found by vector_map loader

### ISSUE THREAD

**Issue by itabrl** [usdot-fhwa-stol/CARMAPlatform#490]
### Types of Issue

- [x] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary
by default libproj is getting installed in the /usr/local/lib which is not the default path for shared libraries in the carma docker images. the default path is /usr/lib. 
### Software version this applies to

3.2.0
### Steps to reproduce the behavior

1. launch the map file loader using the following : 
```roslaunch map_file lanelet2_map_loader.launch file_name:=/opt/carma/maps/vector_map.osm```

### Related work

Link to related tickets or prior related work here.

**Comment by maefromm** [comment]
@itabrl was this fixed and if so what is the PR#? And if was OBE or non-issue, please explain briefly.
