### ISSUE TITLE
CARMAGarminLidarLiteV3DriverWrapper should publish a message type containing header in trailer_angle topic

### ISSUE THREAD

**Issue by msmcconnell** [usdot-fhwa-stol/CARMAPlatform#491]
### Types of Issue

- [ ] Anomaly report (something appears to not work correctly)
- [x] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary
The trailer angle reported by the CARMAGarminLidarLiteV3DriverWrapper is published as an std_msgs/Float64 message type. It is difficult to use this message type reliably as it does not contain a timestamp which can be used for transform lookups. It should be updated to use a message type containing a header. 
### Expected behavior
trailer_angle reported with timestamp
### Software version this applies to

CARMASystem_3.2.0
### Actual behavior
No timestamp reported
### Steps to reproduce the behavior
Look at source code.

**Comment by aswath1** [comment]
fixed under https://github.com/usdot-fhwa-stol/CARMAGarminLidarLiteV3DriverWrapper/pull/12

**Comment by msmcconnell** [comment]
@aswath1 don't close the issue until the PRs have been merged
