### ISSUE TITLE
Velodyne Driver Registration Not Functional On Truck

### ISSUE THREAD

**Issue by Supraluminal** [usdot-fhwa-stol/CARMAPlatform#498]
### Types of Issue

- [x] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary
The Red Freightliner Cascadia configuration appears to map the Veldoyne driver registration topic slightly differently resulting in the driver status message not making it to the `health_checker` node. This results in system shutdown before CARMA can fully initialize.

### Expected behavior

1. Start CARMA via `carma start all`
1. `health_checker` receives driver registration from Velodyne LiDAR drivers
1. CARMA Platform successfully starts up.

### Software version this applies to

CARMASystem_3.2.0, modified to run on the truck as shown on the develop branch of the CARMAConfig repo.

### Actual behavior

1. Start CARMA via `carma start all`
1. `health_checker` does not receive driver registration from Velodyne LiDAR drivers
1. CARMA Platform shuts down.

### Steps to reproduce the behavior

1. Deploy the truck config
1. Run `carma start all`

**Comment by maefromm** [comment]
Related to the red truck integration testing at ATEF on January 2020.
