### ISSUE TITLE
carma_build script broken on autoware.ai fork v1.13

### ISSUE THREAD

**Issue by msmcconnell** [usdot-fhwa-stol/CARMAPlatform#506]
### Types of Issue

- [x] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary
carma_build script does not build autoware properly after moving to autoware 1.13
### Expected behavior
Script can be used to create complete carma and autoware build
### Software version this applies to

CARMASystem 3.2.0
### Actual behavior
Script will not be able to find the carma_autoware_build script in the autoware.ai fork repo. 
### Steps to reproduce the behavior
run 
```
./carma_build -c <carma workspace> -a <path to autoware.ai folder>
```

NOTE: Docker builds do not fail because that uses the prebuilt autoware binaries allowing usage of the -x option with the carma_build script.

**Comment by qswawrq** [comment]
Closed because #507 is merged.
