### ISSUE TITLE
vector map to be loaded when carma is launched

### ISSUE THREAD

**Issue by itabrl** [usdot-fhwa-stol/CARMAPlatform#517]
### Types of Issue

- [ ] Anomaly report (something appears to not work correctly)
- [X] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary
After running carma start all, vector map needs to get loaded. 

### Software version this applies to

3.2.0
### Actual behavior
vector map does not get loaded
### Steps to reproduce the behavior

does not apply

### Related work

Link to related tickets or prior related work here.

**Comment by maefromm** [comment]
This was fixed under https://github.com/usdot-fhwa-stol/autoware.ai/pull/45

**Comment by maefromm** [comment]
Also https://github.com/usdot-fhwa-stol/autoware.ai/pull/55

**Comment by maefromm** [comment]
@itabrl please include fix for rviz profile to include "LaneLet2" display.
