### ISSUE TITLE
Need trailer angle sensor for trucks

### ISSUE THREAD

**Issue by TonysCousin** [usdot-fhwa-stol/CARMAPlatform#518]
### Types of Issue

- [ ] Anomaly report (something appears to not work correctly)
- [x] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary
In order to have a realistic model of the articulated heavy trucks (class 8 tractor-trailer), we need a way to measure the angle of the trailer centerline with respect to the cab centerline and make this angle available to the Carma guidance computer.

### Expected behavior
Sensor continuously reports trailer angle to the computer.

### Software version this applies to

3.1.0

**Comment by maefromm** [comment]
This has been closed by the initial implementation of the CARMAGarminLidarLiteV3DriverWarpper 
Initial PR associated with this is 
https://github.com/usdot-fhwa-stol/CARMAGarminLidarLiteV3DriverWrapper/pull/1#partial-pull-merging

And now the component release has closed this issue. 
https://github.com/usdot-fhwa-stol/CARMAGarminLidarLiteV3DriverWrapper/pull/11
