### ISSUE TITLE
Master version 2.8.0 is ahead of develop

### ISSUE THREAD

**Issue by msmcconnell** [usdot-fhwa-stol/CARMAPlatform#53]
### Descriptive summary
A hot fix with master version 2.8.0 has caused the develop branch to be behind in the commit history. Master must be merged back into develop to resolve this
### Expected behavior
N/A
### Actual behavior
N/A
### Steps to reproduce the behavior
N/A
### Related work
Issue created by hotfix PR #48

**Comment by TonysCousin** [comment]
The only things added to master since the two were synced is documentation. As soon as the latest doc updates are merged, master will be merged into develop.
