### ISSUE TITLE
Blue Lexus bumps curb using 3.2.0

### ISSUE THREAD

**Issue by Supraluminal** [usdot-fhwa-stol/CARMAPlatform#544]
### Types of Issue

- [x] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary
The Blue Lexus bumps the curb during the operation of the normal demo configuration using CARMA 3.2.0 and the old TFHRC map and route. The vehicle travels the TFHRCPrimaryRoute from the C-Hub to after the second intersection. During the left turn through the intersection it cuts the turn a bit too wide and the right front wheel rides up on the curb briefly. This behavior is observed with the old map and route which should be aligned in the same coordinate system. 

### Expected behavior
Lexus does not bump against any objects during it's normal operation
### Software version this applies to

CARMASystem_3.2.0
### Actual behavior
Lexus contacts curb with front right wheel during route execution.

### Steps to reproduce the behavior

1. Deploy `CARMASystem_3.2.0...lexus` CARMAConfig
2. Load old TFHRC PCD map and ensure that TFHRCPrimaryRoute is available
3. Start carma and engage the TFHRCPrimaryRoute

**Comment by maefromm** [comment]
Saina mentioned that Pavle and her tested the Blue Lexus yesterday using 3.2.0 and it did not bump the curb. Therefore we are closing the Github Issue #544. And if this happens again, I think #543 issue will cover this.
