### ISSUE TITLE
Update Autoware fork to reflect the official 1.13 release

### ISSUE THREAD

**Issue by saina-ramyar** [usdot-fhwa-stol/CARMAPlatform#634]
### Types of Issue

- [ ] Anomaly report (something appears to not work correctly)
- [x] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary
Autoware fork is updated to reflect the official 1.13 release.
### Expected behavior
CARMA starts and runs stably with this Autoware fork.

**Comment by TonysCousin** [comment]
Issue closed due to completion of work and merging of PR #90 in the autoware.ai repo.
