### ISSUE TITLE
URDF file comments are innacurate

### ISSUE THREAD

**Issue by Supraluminal** [usdot-fhwa-stol/CARMAPlatform#78]
### Descriptive summary
The comments in the URDF files describe the configuration as being for the green Cadillac when they are generic to all Cadillacs.

### Expected behavior
N/A
### Actual behavior
N/A
### Steps to reproduce the behavior
N/A
### Related work
N/A

**Comment by msmcconnell** [comment]
Close as OBE in carma3 and the comments were verified on the vehicle calibration repo
